"""Bazel rules for building OS images with mkosi."""

module(
    name = "rules_mkosi",
    bazel_compatibility = [">=7.0.0"],
)

# Runtime dependencies. These are minimum versions for module resolution.
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

mkosi = use_extension("//mkosi:extensions.bzl", "mkosi")
mkosi.toolchain()
use_repo(mkosi, "mkosi_toolchains")

register_toolchains("@mkosi_toolchains//:all")
