exports_files([
    "defs.bzl",
    "extensions.bzl",
    "qemu_toolchain.bzl",
    "qemu_versions.bzl",
    "toolchain.bzl",
    "versions.bzl",
    "version.bzl",
])

alias(
    name = "kernel_preflight",
    actual = "//mkosi/private:kernel_preflight",
    visibility = ["//visibility:public"],
)
