module(name = "mkosi_extension_nonroot_name")

bazel_dep(name = "rules_mkosi", version = "0.0.0")
local_path_override(
    module_name = "rules_mkosi",
    path = "../../..",
)

bazel_dep(name = "hermetic_cc_toolchain", version = "4.3.0")

hermetic_cc = use_extension(
    "@hermetic_cc_toolchain//toolchain:ext.bzl",
    "toolchains",
)
hermetic_cc.exec_platform(
    arch = "amd64",
    os = "linux",
)
use_repo(hermetic_cc, "zig_sdk")

register_toolchains("@zig_sdk//toolchain:linux_amd64_musl")

bazel_dep(name = "mkosi_nonroot_dep", version = "0.0.0")
local_path_override(
    module_name = "mkosi_nonroot_dep",
    path = "../nonroot_name_dep",
)

mkosi = use_extension("@rules_mkosi//mkosi:extensions.bzl", "mkosi")
mkosi.toolchain()
