module(name = "mkosi_extension_conflicting_root")

bazel_dep(name = "rules_mkosi", version = "0.0.0")
local_path_override(
    module_name = "rules_mkosi",
    path = "../../..",
)

mkosi = use_extension("@rules_mkosi//mkosi:extensions.bzl", "mkosi")
mkosi.toolchain(name = "mkosi")
mkosi.toolchain(name = "alternate")
