load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@rules_mkosi//mkosi:defs.bzl", "mkosi_image")

mkosi_image(
    name = "demo",
    distribution = "debian",
)

build_test(
    name = "demo_build_test",
    targets = [":demo"],
)

build_test(
    name = "kernel_preflight_build_test",
    targets = ["@rules_mkosi//mkosi:kernel_preflight"],
)

diff_test(
    name = "demo_content_test",
    file1 = "testdata/debian.image.golden.txt",
    file2 = ":demo",
)

mkosi_image(
    name = "ubuntu_demo",
    distribution = "ubuntu",
)

diff_test(
    name = "ubuntu_demo_content_test",
    file1 = "testdata/ubuntu.image.golden.txt",
    file2 = ":ubuntu_demo",
)
