load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@rules_mkosi//mkosi:defs.bzl", "mkosi_image", "qemu_ovmf_smoke_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

mkosi_image(
    name = "demo",
    distribution = "debian",
)

build_test(
    name = "demo_build_test",
    targets = [":demo"],
)

build_test(
    name = "kernel_preflight_build_test",
    targets = ["@rules_mkosi//mkosi:kernel_preflight"],
)

diff_test(
    name = "demo_content_test",
    file1 = "testdata/debian.image.golden.txt",
    file2 = ":demo",
)

sh_test(
    name = "mkosi_version_test",
    srcs = ["mkosi_version_test.sh"],
    data = [
        "sitecustomize.py",
        "@mkosi_toolchains//:mkosi",
    ],
)

qemu_ovmf_smoke_test(
    name = "qemu_ovmf_smoke_test",
)

mkosi_image(
    name = "ubuntu_demo",
    distribution = "ubuntu",
)

diff_test(
    name = "ubuntu_demo_content_test",
    file1 = "testdata/ubuntu.image.golden.txt",
    file2 = ":ubuntu_demo",
)
