load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "workflow_bazel_command_test",
    srcs = ["workflow_bazel_command_test.py"],
    args = ["$(rootpath //:.github/workflows/ci.yml)"],
    data = ["//:.github/workflows/ci.yml"],
    main = "workflow_bazel_command_test.py",
    deps = ["@mkosi_pypi//pyyaml"],
)

py_test(
    name = "workflow_bazel_command_parser_test",
    srcs = [
        "workflow_bazel_command_parser_test.py",
        "workflow_bazel_command_test.py",
    ],
    main = "workflow_bazel_command_parser_test.py",
    deps = ["@mkosi_pypi//pyyaml"],
)

py_test(
    name = "action_graph_validator_test",
    srcs = [
        "action_graph_validator.py",
        "action_graph_validator_test.py",
    ],
    main = "action_graph_validator_test.py",
)
