load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("//mkosi:defs.bzl", "mkosi_image")
load(":mkosi_image_test.bzl", "mkosi_image_test_suite")

mkosi_image_test_suite(name = "analysis_tests")

mkosi_image(
    name = "golden_image",
    distribution = "debian",
)

diff_test(
    name = "golden_image_test",
    file1 = "testdata/debian.image.golden.txt",
    file2 = ":golden_image",
)

mkosi_image(
    name = "ubuntu_golden_image",
    distribution = "ubuntu",
)

diff_test(
    name = "ubuntu_golden_image_test",
    file1 = "testdata/ubuntu.image.golden.txt",
    file2 = ":ubuntu_golden_image",
)
