#!/bin/sh
set -eux
echo RULES_MKOSI_SLOT_A_VERSION=1
mkdir -p /run/rules-mkosi-update
mount -t 9p -o trans=virtio,ro rules_mkosi_updates /run/rules-mkosi-update
/usr/bin/systemd-repart --dry-run=no --definitions=/usr/lib/rules-mkosi-repart.d /dev/vda
cd /run/rules-mkosi-update/source
sha256sum -c SHA256SUMS
echo RULES_MKOSI_UPDATE_DIGESTS_VERIFIED
/usr/lib/systemd/systemd-sysupdate --definitions=/run/rules-mkosi-update/definitions --transfer-source=/run/rules-mkosi-update/source --verify=yes update 2
echo RULES_MKOSI_SYSUPDATE_APPLIED_VERSION=2
touch /efi/rules-mkosi-update-applied
sync
systemctl poweroff
